package net.sonclub.shiro

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    static nonAuthenticatedActions = [
            [controller: 'wechatApi', action: 'input'],
            [controller: 'wechatApi', action: 'output'],
            [controller: 'user', action: 'auth']
    ]

    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                def needsAuth = nonAuthenticatedActions.find {
                    (it.controller == controllerName) &&
                            ((it.action == '*') || (it.action == actionName))
                }
                if (needsAuth) return true

                // Access control by convention.
                accessControl()
            }
        }
    }
}
